# Generated by Django 2.1.15 on 2020-02-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birthPlace', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': '"Athlete\'s tables"."Athletes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"Athlete\'s tables"."Coaches"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoLink', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"Event\'s tables"."Events"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventVideoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"Student\'s tables"."Event_video_comments"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('photo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': '"Athlete\'s tables"."Sports"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SportModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"Athlete\'s tables"."Sport_Modalities"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"Student\'s tables"."Students"',
                'managed': False,
            },
        ),
    ]
