# Generated by Django 2.1.15 on 2020-02-03 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(db_column='names', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('birthDate', models.DateField(db_column='birth_date')),
                ('birthPlace', models.CharField(db_column='birth_place', max_length=100)),
                ('weight', models.FloatField(db_column='weight')),
                ('height', models.FloatField(db_column='height')),
                ('photo', models.CharField(db_column='photo', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(db_column='result', max_length=20)),
                ('athlete', models.ForeignKey(db_column='id_athlete', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(db_column='id_athlete', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoLink', models.CharField(db_column='video_link', max_length=100)),
                ('eventDate', models.DateField(db_column='event_date', default=django.utils.timezone.now)),
                ('eventTime', models.TimeField(db_column='event_time', default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventVideoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(db_column='creation_date', default=django.utils.timezone.now)),
                ('comment', models.CharField(db_column='comment', max_length=500, null=True)),
                ('event', models.ForeignKey(db_column='id_event', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=60, null=True)),
                ('photo', models.CharField(db_column='photo', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=60, null=True)),
                ('sport', models.ForeignKey(db_column='id_sport', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=60)),
                ('password', models.CharField(db_column='password', max_length=60)),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='eventvideocomments',
            name='student',
            field=models.ForeignKey(db_column='id_student', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(db_column='id_sport', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Sport'),
        ),
        migrations.AddField(
            model_name='event',
            name='sportModality',
            field=models.ForeignKey(db_column='id_sport_modality', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.SportModality'),
        ),
        migrations.AddField(
            model_name='athletesport',
            name='sport',
            field=models.ForeignKey(db_column='id_sport', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Sport'),
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='event',
            field=models.ForeignKey(db_column='id_event', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Event'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(db_column='id_coach', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio2020.Coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.ManyToManyField(through='tokio2020.AthleteSport', to='tokio2020.Sport'),
        ),
    ]
