# Generated by Django 2.1.15 on 2020-02-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0002_auto_20200202_1425'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='athleteevent',
            table='"Event\'sTables"."athlete_event"',
        ),
        migrations.AlterModelTable(
            name='athletes',
            table='"Athlete\'sTables"."athletes"',
        ),
        migrations.AlterModelTable(
            name='coaches',
            table='"Athlete\'sTables"."coaches"',
        ),
        migrations.AlterModelTable(
            name='event',
            table='"Event\'sTables"."events"',
        ),
        migrations.AlterModelTable(
            name='eventvideocomments',
            table='"Student\'sTables"."event_video_comments"',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='"Athlete\'sTables"."sports"',
        ),
        migrations.AlterModelTable(
            name='sportmodality',
            table='"Athlete\'sTables"."sport_modalities"',
        ),
        migrations.AlterModelTable(
            name='student',
            table='"Student\'sTables"."students"',
        ),
    ]
