# Generated by Django 2.1.15 on 2020-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0003_auto_20200202_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(db_column='names', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('birthDate', models.DateField(db_column='birth_date')),
                ('birthPlace', models.CharField(db_column='birth_place', max_length=100)),
                ('weight', models.FloatField(db_column='weight')),
                ('height', models.FloatField(db_column='height')),
                ('photo', models.CharField(db_column='photo', max_length=300)),
            ],
            options={
                'db_table': '"Athlete\'sTables"."athletes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
            ],
            options={
                'db_table': '"Athlete\'sTables"."coaches"',
                'managed': False,
            },
        ),
    ]
