# Generated by Django 2.1.15 on 2020-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0004_athlete_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"Event\'sTables"."Athletes_sports"',
                'managed': False,
            },
        ),
    ]
