# Generated by Django 2.1.15 on 2020-02-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0005_athletesport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='athletesport',
            table='"Athlete\'sTables"."athletes_sports"',
        ),
    ]
